# PASSO A PASSO DA API

- INICIAR O PROJETO, YARN INIT -Y

- CRIAR OS SCRIPSTS NO PACKAGE.JSON

- CRIAR O SERVER AONDE FICA CENTRALIZADO TUDO

- INSTALAR AS DEPENDENCIAS 
    - MONGOOSE
    - NODEMON
    - REQUIREDIR
    - EXPRESS

- CRIAR A PASTA SRC
    - FICA OS CONTROLLERS
    - OS MODELS
        - FICA OS SCHEMAS
    -E AS ROTAS

INSTALAR O DOCKER QUE FICARA A MAQUNA VIRTUAL ONDE TA O BANCO DE DADOS
INSTALAR O ROBO3T PRA VER AS TABELAS
INSTALAR O MONGOOOSE PAGINATE
e instalar o cors